name: ruby

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruby-qa:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: sinatra
          POSTGRES_PASSWORD: sinatra
          LC_ALL: C.UTF-8
          LANG: en_US.UTF-8
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RACK_ENV: test
      DATABASE_URL: localhost
      DATABASE_USER: sinatra
      DATABASE_PASSWORD: sinatra

    strategy:
      fail-fast: false
      matrix:
        ruby: ["ruby-3.3"]
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup database
        run: bundle exec rake db:setup

      - name: Rubocop
        run: bundle exec rubocop

      - name: Run tests
        run: bundle exec rake test
